version: "3.9"
services:
  pg:
    image: ankane/pgvector:latest
    container_name: khobor-pg
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: khobor
    ports: ["5432:5432"]
    volumes: ["./.pgdata:/var/lib/postgresql/data"]
